feat: changes in readme
nodejs/nodejs-pt pull request #77
Opened 2019-01-19 03:12 UTC by verneck

made some modifications in the readme add badges and formatting the text

2019-01-19 03:18 UTC, glaucia86 commented on README.md
> +# NODEJS PT-BR
```suggestion
nodejs-pt
```
deixa explicar porque... por conta do padrão que está delimitado no link do io.js. Veja aqui: https://github.com/nodejs/nodejs.org/blob/master/TRANSLATION.md

2019-01-19 03:22 UTC, glaucia86 commented on README.md
> +# NODEJS PT-BR
@gustavohenke oq acha dessa mudança q o @verneck está propondo?

2019-01-19 03:25 UTC, glaucia86 reviewed
@gustavohenke @JCMais @Drieger o que acham das mudanças que o @verneck está propondo?
Com respeito a uso de imagem... acho q tem um lugar que fala onde poderá ser obtida a imagem.... na documentação do Node.js. Tem um padrão de uso. @gustavohenke vc q está mais tempo.. confirma isso? 

LINK logos: **[Logos](https://github.com/nodejs/nodejs.org/tree/master/static/images/logos)**

2019-01-19 10:04 UTC, gustavohenke requested changes

2019-01-19 10:04 UTC, gustavohenke commented on README.md
> +# NODEJS PT-BR
A comunidade é para falantes de português, não apenas brasileiros. Minha recomendação é "Node.js em português".

2019-01-20 02:00 UTC, verneck commented
@gustavohenke @glaucia86 da uma olhada se agora está ok

2019-01-20 02:01 UTC, glaucia86 commented on README.md
> +# NODEJS EM PORTUGUÉS
```suggestion
# NODEJS EM PORTUGUÊS
```

2019-01-20 02:02 UTC, glaucia86 commented on README.md
> +# NODEJS EM PORTUGUÉS
Só altera o acento @verneck 
Daí aprovo aqui agora.

2019-01-20 02:03 UTC, glaucia86 approved these changes
LGTM 👍

2019-01-20 03:45 UTC, verneck commented on README.md
> +# NODEJS EM PORTUGUÉS
já está acertado!

2019-01-21 00:27 UTC, JCMais approved these changes

2019-01-21 03:10 UTC, glaucia86 commented
@gustavohenke pode dar uma olhada e ver se agora está bom?

2019-01-21 03:33 UTC, gustavohenke approved these changes
Está ótimo, obrigado pela retocada no README 😛

2019-01-21 10:44 UTC, verneck commented
@gustavohenke farei mais alguns ajustes e etc.

2019-01-21 10:56 UTC, glaucia86 commented
> @gustavohenke farei mais alguns ajustes e etc.

Muito obrigada pela sua contribuição @verneck :)

2019-01-21 10:57 UTC, merged

2019-01-21 12:27 UTC, verneck commented
@glaucia86 @gustavohenke eu que agradeço por poder estar contribuindo com o proejeto.